// Auto-generated product database
const allProjectProducts = [
  {
    name: "Anniversary Gift",
    price: 400,
    category: "Anniversary",
    image: "/gifts/Anniversary 2.avif",
    description: "Premium Anniversary gift: Anniversary Gift.",
  },
  {
    name: "Anniversary Gift",
    price: 500,
    category: "Anniversary",
    image: "/gifts/Anniversary 3.avif",
    description: "Premium Anniversary gift: Anniversary Gift.",
  },
  {
    name: "Anniversary Gift",
    price: 600,
    category: "Anniversary",
    image: "/gifts/Anniversary 4.jpeg",
    description: "Premium Anniversary gift: Anniversary Gift.",
  },
  {
    name: "Anniversary Gift",
    price: 700,
    category: "Anniversary",
    image: "/gifts/Anniversary 5.jpeg",
    description: "Premium Anniversary gift: Anniversary Gift.",
  },
  {
    name: "Anniversary Gift",
    price: 800,
    category: "Anniversary",
    image: "/gifts/Anniversary 10.avif",
    description: "Premium Anniversary gift: Anniversary Gift.",
  },
  {
    name: "Wedding Keepsake",
    price: 800,
    category: "Wedding",
    image: "/gifts/Couple Gift 1.avif",
    description: "Premium Wedding gift: Wedding Keepsake.",
  },
  {
    name: "Wedding Ring Box",
    price: 950,
    category: "Wedding",
    image: "/gifts/Couple Gift 2.avif",
    description: "Premium Wedding gift: Wedding Ring Box.",
  },
  {
    name: "Wedding Moment Frame",
    price: 1200,
    category: "Wedding",
    image: "/gifts/Couple Gift 5.avif",
    description: "Premium Wedding gift: Wedding Moment Frame.",
  },
  {
    name: "Wedding Celebration Set",
    price: 1400,
    category: "Wedding",
    image: "/gifts/Couple Gift 7.avif",
    description: "Premium Wedding gift: Wedding Celebration Set.",
  },
  {
    name: "Wedding Duo Gift",
    price: 1750,
    category: "Wedding",
    image: "/gifts/Couple Gift 9.avif",
    description: "Premium Wedding gift: Wedding Duo Gift.",
  },
  {
    name: "Baby Gift",
    price: 200,
    category: "Baby",
    image: "/gifts/Baby 1.avif",
    description: "Premium Baby gift: Baby Gift.",
  },
  {
    name: "Baby Gift",
    price: 250,
    category: "Baby",
    image: "/gifts/Baby 2.avif",
    description: "Premium Baby gift: Baby Gift.",
  },
  {
    name: "Baby Gift",
    price: 300,
    category: "Baby",
    image: "/gifts/Baby 3.avif",
    description: "Premium Baby gift: Baby Gift.",
  },
  {
    name: "Baby Gift",
    price: 350,
    category: "Baby",
    image: "/gifts/Baby 4.avif",
    description: "Premium Baby gift: Baby Gift.",
  },
  {
    name: "Baby Gift",
    price: 400,
    category: "Baby",
    image: "/gifts/Baby 5.avif",
    description: "Premium Baby gift: Baby Gift.",
  },
  {
    name: "Baby Gift",
    price: 450,
    category: "Baby",
    image: "/gifts/Baby 6.avif",
    description: "Premium Baby gift: Baby Gift.",
  },
  {
    name: "Baby Gift",
    price: 500,
    category: "Baby",
    image: "/gifts/Baby 7.avif",
    description: "Premium Baby gift: Baby Gift.",
  },
  {
    name: "Baby Gift",
    price: 550,
    category: "Baby",
    image: "/gifts/Baby 8.avif",
    description: "Premium Baby gift: Baby Gift.",
  },
  {
    name: "Baby Gift",
    price: 600,
    category: "Baby",
    image: "/gifts/Baby 9.avif",
    description: "Premium Baby gift: Baby Gift.",
  },
  {
    name: "Baby Gift",
    price: 650,
    category: "Baby",
    image: "/gifts/Baby 10.avif",
    description: "Premium Baby gift: Baby Gift.",
  },
  {
    name: "Toy",
    price: 700,
    category: "Baby",
    image: "/gifts/Toy 1.avif",
    description: "Premium Baby gift: Toy.",
  },
  {
    name: "Toy",
    price: 750,
    category: "Baby",
    image: "/gifts/Toy 2.avif",
    description: "Premium Baby gift: Toy.",
  },
  {
    name: "Toy",
    price: 800,
    category: "Baby",
    image: "/gifts/Toy 3.avif",
    description: "Premium Baby gift: Toy.",
  },
  {
    name: "Toy",
    price: 850,
    category: "Baby",
    image: "/gifts/Toy 4.avif",
    description: "Premium Baby gift: Toy.",
  },
  {
    name: "Toy",
    price: 900,
    category: "Baby",
    image: "/gifts/Toy 5.avif",
    description: "Premium Baby gift: Toy.",
  },
  {
    name: "Toy",
    price: 950,
    category: "Baby",
    image: "/gifts/Toy 6.avif",
    description: "Premium Baby gift: Toy.",
  },
  {
    name: "Birthday Gift",
    price: 300,
    category: "Birthday",
    image: "./gifts/Birthday 1.avif",
    description: "Premium Birthday gift: Birthday Gift.",
  },
  {
    name: "Couple Gift",
    price: 300,
    category: "Couple",
    image: "/gifts/Couple Gift 1.avif",
    description: "Premium Couple gift: Couple Gift.",
  },
  {
    name: "Couple Gift",
    price: 350,
    category: "Couple",
    image: "/gifts/Couple Gift 2.avif",
    description: "Premium Couple gift: Couple Gift.",
  },
  {
    name: "Couple Gift",
    price: 400,
    category: "Couple",
    image: "/gifts/Couple gift 3.avif",
    description: "Premium Couple gift: Couple Gift.",
  },
  {
    name: "Couple Gift",
    price: 450,
    category: "Couple",
    image: "/gifts/Couple Gift 4.avif",
    description: "Premium Couple gift: Couple Gift.",
  },
  {
    name: "Couple Gift",
    price: 500,
    category: "Couple",
    image: "/gifts/Couple Gift 5.avif",
    description: "Premium Couple gift: Couple Gift.",
  },
  {
    name: "Couple Gift",
    price: 550,
    category: "Couple",
    image: "/gifts/couple Gift 6.avif",
    description: "Premium Couple gift: Couple Gift.",
  },
  {
    name: "Couple Gift",
    price: 600,
    category: "Couple",
    image: "/gifts/Couple Gift 7.avif",
    description: "Premium Couple gift: Couple Gift.",
  },
  {
    name: "Couple Gift",
    price: 650,
    category: "Couple",
    image: "/gifts/Couple Gift 8.avif",
    description: "Premium Couple gift: Couple Gift.",
  },
  {
    name: "Couple Gift",
    price: 700,
    category: "Couple",
    image: "/gifts/Couple Gift 9.avif",
    description: "Premium Couple gift: Couple Gift.",
  },
  {
    name: "Couple Gift",
    price: 750,
    category: "Couple",
    image: "/gifts/couple Gift 10.avif",
    description: "Premium Couple gift: Couple Gift.",
  },
  {
    name: "Creative Gift",
    price: 500,
    category: "Creative",
    image: "/gifts/Creative 1.avif",
    description: "Premium Creative gift: Creative Gift.",
  },
  {
    name: "Creative Gift",
    price: 550,
    category: "Creative",
    image: "/gifts/Creative 2.avif",
    description: "Premium Creative gift: Creative Gift.",
  },
  {
    name: "Creative Gift",
    price: 600,
    category: "Creative",
    image: "/gifts/Creative 3.avif",
    description: "Premium Creative gift: Creative Gift.",
  },
  {
    name: "Creative Gift",
    price: 650,
    category: "Creative",
    image: "/gifts/Creative 4.avif",
    description: "Premium Creative gift: Creative Gift.",
  },
  {
    name: "Creative Gift",
    price: 700,
    category: "Creative",
    image: "/gifts/Creative 5.avif",
    description: "Premium Creative gift: Creative Gift.",
  },
  {
    name: "Creative Gift",
    price: 750,
    category: "Creative",
    image: "/gifts/Creative 6.avif",
    description: "Premium Creative gift: Creative Gift.",
  },
  {
    name: "Creative Gift",
    price: 800,
    category: "Creative",
    image: "/gifts/Creative 7.avif",
    description: "Premium Creative gift: Creative Gift.",
  },
  {
    name: "Creative Gift",
    price: 850,
    category: "Creative",
    image: "/gifts/Creative 8.avif",
    description: "Premium Creative gift: Creative Gift.",
  },
  {
    name: "Creative Gift",
    price: 900,
    category: "Creative",
    image: "/gifts/Creative 9.avif",
    description: "Premium Creative gift: Creative Gift.",
  },
  {
    name: "Festival Gift",
    price: 200,
    category: "Festival",
    image: "/gifts/Festival Gifts.avif",
    description: "Premium Festival gift: Festival Gift.",
  },
  {
    name: "Sweet Box",
    price: 250,
    category: "Festival",
    image: "/gifts/Sweet Box 1.jpg",
    description: "Premium Festival gift: Sweet Box.",
  },
  {
    name: "Sweet Box",
    price: 300,
    category: "Festival",
    image: "/gifts/Sweet Box 2.jpg",
    description: "Premium Festival gift: Sweet Box.",
  },
  {
    name: "Sweet Box",
    price: 350,
    category: "Festival",
    image: "/gifts/Sweet Box 3.jpg",
    description: "Premium Festival gift: Sweet Box.",
  },
  {
    name: "Sweet Box",
    price: 400,
    category: "Festival",
    image: "/gifts/Sweet Box 4.jpg",
    description: "Premium Festival gift: Sweet Box.",
  },
  {
    name: "Sweet Box",
    price: 450,
    category: "Festival",
    image: "/gifts/Sweet Box 5.jpg",
    description: "Premium Festival gift: Sweet Box.",
  },
  {
    name: "Sweet Box",
    price: 500,
    category: "Festival",
    image: "/gifts/Sweet Box 6.jpg",
    description: "Premium Festival gift: Sweet Box.",
  },
  {
    name: "Sweet Box",
    price: 550,
    category: "Festival",
    image: "/gifts/Sweet Box 7.jpg",
    description: "Premium Festival gift: Sweet Box.",
  },
  {
    name: "Sweet Box",
    price: 600,
    category: "Festival",
    image: "/gifts/Sweet Box 8.avif",
    description: "Premium Festival gift: Sweet Box.",
  },
  {
    name: "Sweet Box",
    price: 650,
    category: "Festival",
    image: "/gifts/Sweet Box 9.avif",
    description: "Premium Festival gift: Sweet Box.",
  },
  {
    name: "Sweet Box",
    price: 700,
    category: "Festival",
    image: "/gifts/Sweet Box 10.avif",
    description: "Premium Festival gift: Sweet Box.",
  },
  {
    name: "Fitness Gift",
    price: 600,
    category: "Fitness",
    image: "/gifts/Fitness 1.avif",
    description: "Premium Fitness gift: Fitness Gift.",
  },
  {
    name: "Fitness Gift",
    price: 650,
    category: "Fitness",
    image: "/gifts/Fitness 2.avif",
    description: "Premium Fitness gift: Fitness Gift.",
  },
  {
    name: "Fitness Gift",
    price: 700,
    category: "Fitness",
    image: "/gifts/Fitness 3.avif",
    description: "Premium Fitness gift: Fitness Gift.",
  },
  {
    name: "Fitness Gift",
    price: 750,
    category: "Fitness",
    image: "/gifts/Fitness 4.avif",
    description: "Premium Fitness gift: Fitness Gift.",
  },
  {
    name: "Fitness Gift",
    price: 800,
    category: "Fitness",
    image: "/gifts/Fitness 5.avif",
    description: "Premium Fitness gift: Fitness Gift.",
  },
  {
    name: "Fitness Gift",
    price: 850,
    category: "Fitness",
    image: "/gifts/Fitness 6.avif",
    description: "Premium Fitness gift: Fitness Gift.",
  },
  {
    name: "Fitness Gift",
    price: 900,
    category: "Fitness",
    image: "/gifts/Fitness 7.avif",
    description: "Premium Fitness gift: Fitness Gift.",
  },
  {
    name: "Fitness Gift",
    price: 950,
    category: "Fitness",
    image: "/gifts/Fitness 8.avif",
    description: "Premium Fitness gift: Fitness Gift.",
  },
  {
    name: "Fitness Gift",
    price: 1000,
    category: "Fitness",
    image: "/gifts/Fitness 9.avif",
    description: "Premium Fitness gift: Fitness Gift.",
  },
  {
    name: "Fitness Gift",
    price: 1050,
    category: "Fitness",
    image: "/gifts/Fitness 10.avif",
    description: "Premium Fitness gift: Fitness Gift.",
  },
  {
    name: "Friendship Gift",
    price: 300,
    category: "Friendship",
    image: "/gifts/Friendship 1.avif",
    description: "Premium Friendship gift: Friendship Gift.",
  },
  {
    name: "Friendship Gift",
    price: 350,
    category: "Friendship",
    image: "/gifts/Frienship 2.avif",
    description: "Premium Friendship gift: Friendship Gift.",
  },
  {
    name: "Friendship Gift",
    price: 400,
    category: "Friendship",
    image: "/gifts/Friendship 3.avif",
    description: "Premium Friendship gift: Friendship Gift.",
  },
  {
    name: "Friendship Gift",
    price: 450,
    category: "Friendship",
    image: "/gifts/Friendship 4.avif",
    description: "Premium Friendship gift: Friendship Gift.",
  },
  {
    name: "General Gift",
    price: 200,
    category: "General",
    image: "/gifts/General Gifts.avif",
    description: "Premium General gift: General Gift.",
  },
  {
    name: "Bottle",
    price: 250,
    category: "General",
    image: "/gifts/Bottle 1.jpeg",
    description: "Premium General gift: Bottle.",
  },
  {
    name: "Chocolate",
    price: 300,
    category: "General",
    image: "/gifts/Chocolate 1.avif",
    description: "Premium General gift: Chocolate.",
  },
  {
    name: "Chocolate",
    price: 350,
    category: "General",
    image: "/gifts/Chocolate 2.avif",
    description: "Premium General gift: Chocolate.",
  },
  {
    name: "Chocolate",
    price: 400,
    category: "General",
    image: "/gifts/Chocolate 3.avif",
    description: "Premium General gift: Chocolate.",
  },
  {
    name: "Chocolate",
    price: 450,
    category: "General",
    image: "/gifts/Chocolate 4.avif",
    description: "Premium General gift: Chocolate.",
  },
  {
    name: "Chocolate",
    price: 500,
    category: "General",
    image: "/gifts/Chocolate 5.avif",
    description: "Premium General gift: Chocolate.",
  },
  {
    name: "Chocolate",
    price: 550,
    category: "General",
    image: "/gifts/Chocolate 6.avif",
    description: "Premium General gift: Chocolate.",
  },
  {
    name: "Chocolate",
    price: 600,
    category: "General",
    image: "/gifts/Chocolate 7.avif",
    description: "Premium General gift: Chocolate.",
  },
  {
    name: "Chocolate",
    price: 650,
    category: "General",
    image: "/gifts/Chocolate 8.avif",
    description: "Premium General gift: Chocolate.",
  },
  {
    name: "Chocolate",
    price: 700,
    category: "General",
    image: "/gifts/Chocolate 9.avif",
    description: "Premium General gift: Chocolate.",
  },
  {
    name: "Chocolate",
    price: 750,
    category: "General",
    image: "/gifts/Chocolate 10.avif",
    description: "Premium General gift: Chocolate.",
  },
  {
    name: "Purse",
    price: 800,
    category: "General",
    image: "/gifts/Purse 1.avif",
    description: "Premium General gift: Purse.",
  },
  {
    name: "Purse",
    price: 850,
    category: "General",
    image: "/gifts/Purse 2.avif",
    description: "Premium General gift: Purse.",
  },
  {
    name: "Purse",
    price: 900,
    category: "General",
    image: "/gifts/Purse 3.avif",
    description: "Premium General gift: Purse.",
  },
  {
    name: "Purse",
    price: 950,
    category: "General",
    image: "/gifts/Purse 4.avif",
    description: "Premium General gift: Purse.",
  },
  {
    name: "Purse",
    price: 1000,
    category: "General",
    image: "/gifts/Purse 5.avif",
    description: "Premium General gift: Purse.",
  },
  {
    name: "Purse",
    price: 1050,
    category: "General",
    image: "/gifts/Purse 6.avif",
    description: "Premium General gift: Purse.",
  },
  {
    name: "Purse",
    price: 1100,
    category: "General",
    image: "/gifts/Purse 7.avif",
    description: "Premium General gift: Purse.",
  },
  {
    name: "Purse",
    price: 1150,
    category: "General",
    image: "/gifts/Purse 8.avif",
    description: "Premium General gift: Purse.",
  },
  {
    name: "Purse",
    price: 1200,
    category: "General",
    image: "/gifts/Purse 9.avif",
    description: "Premium General gift: Purse.",
  },
  {
    name: "Purse",
    price: 1250,
    category: "General",
    image: "/gifts/Purse 10.avif",
    description: "Premium General gift: Purse.",
  },
  {
    name: "Wallet",
    price: 1300,
    category: "General",
    image: "/gifts/Wallet 1.avif",
    description: "Premium General gift: Wallet.",
  },
  {
    name: "Wallet",
    price: 1350,
    category: "General",
    image: "/gifts/Wallet 2.avif",
    description: "Premium General gift: Wallet.",
  },
  {
    name: "Wallet",
    price: 1400,
    category: "General",
    image: "/gifts/Wallet 3.avif",
    description: "Premium General gift: Wallet.",
  },
  {
    name: "Wallet",
    price: 1450,
    category: "General",
    image: "/gifts/Wallet 4.avif",
    description: "Premium General gift: Wallet.",
  },
  {
    name: "Wallet",
    price: 1500,
    category: "General",
    image: "/gifts/Wallet 5.avif",
    description: "Premium General gift: Wallet.",
  },
  {
    name: "Wallet",
    price: 1550,
    category: "General",
    image: "/gifts/Wallet 6.avif",
    description: "Premium General gift: Wallet.",
  },
  {
    name: "Wallet",
    price: 1600,
    category: "General",
    image: "/gifts/Wallet 7.avif",
    description: "Premium General gift: Wallet.",
  },
  {
    name: "Wallet",
    price: 1650,
    category: "General",
    image: "/gifts/Wallet 8.avif",
    description: "Premium General gift: Wallet.",
  },
  {
    name: "Wallet",
    price: 1700,
    category: "General",
    image: "/gifts/Wallet 9.avif",
    description: "Premium General gift: Wallet.",
  },
  {
    name: "Wallet",
    price: 1750,
    category: "General",
    image: "/gifts/Wallet 10.avif",
    description: "Premium General gift: Wallet.",
  },
  {
    name: "Home Gift",
    price: 400,
    category: "Home",
    image: "/gifts/Home 1.avif",
    description: "Premium Home gift: Home Gift.",
  },
  {
    name: "Home Gift",
    price: 450,
    category: "Home",
    image: "/gifts/Home 2.avif",
    description: "Premium Home gift: Home Gift.",
  },
  {
    name: "Home Gift",
    price: 500,
    category: "Home",
    image: "/gifts/Home 3.avif",
    description: "Premium Home gift: Home Gift.",
  },
  {
    name: "Home Gift",
    price: 550,
    category: "Home",
    image: "/gifts/Home 4.avif",
    description: "Premium Home gift: Home Gift.",
  },
  {
    name: "Home Gift",
    price: 600,
    category: "Home",
    image: "/gifts/Home 5.avif",
    description: "Premium Home gift: Home Gift.",
  },
  {
    name: "Home Gift",
    price: 650,
    category: "Home",
    image: "/gifts/Home 6.avif",
    description: "Premium Home gift: Home Gift.",
  },
  {
    name: "Home Gift",
    price: 700,
    category: "Home",
    image: "/gifts/Home 7.avif",
    description: "Premium Home gift: Home Gift.",
  },
  {
    name: "Home Gift",
    price: 750,
    category: "Home",
    image: "/gifts/Home 8.avif",
    description: "Premium Home gift: Home Gift.",
  },
  {
    name: "Home Gift",
    price: 800,
    category: "Home",
    image: "/gifts/Home 9.avif",
    description: "Premium Home gift: Home Gift.",
  },
  {
    name: "Home Gift",
    price: 850,
    category: "Home",
    image: "/gifts/Home 10.avif",
    description: "Premium Home gift: Home Gift.",
  },
  {
    name: "Mug",
    price: 900,
    category: "Home",
    image: "/gifts/Mug 1.avif",
    description: "Premium Home gift: Mug.",
  },
  {
    name: "Mug",
    price: 950,
    category: "Home",
    image: "/gifts/Mug 2.avif",
    description: "Premium Home gift: Mug.",
  },
  {
    name: "Mug",
    price: 1000,
    category: "Home",
    image: "/gifts/Mug 3.avif",
    description: "Premium Home gift: Mug.",
  },
  {
    name: "Mug",
    price: 1050,
    category: "Home",
    image: "/gifts/Mug 4.avif",
    description: "Premium Home gift: Mug.",
  },
  {
    name: "Mug",
    price: 1100,
    category: "Home",
    image: "/gifts/Mug 5.avif",
    description: "Premium Home gift: Mug.",
  },
  {
    name: "Mug",
    price: 1150,
    category: "Home",
    image: "/gifts/Mug 6.avif",
    description: "Premium Home gift: Mug.",
  },
  {
    name: "Mug",
    price: 1200,
    category: "Home",
    image: "/gifts/Mug 7.avif",
    description: "Premium Home gift: Mug.",
  },
  {
    name: "Mug",
    price: 1250,
    category: "Home",
    image: "/gifts/Mug 8.avif",
    description: "Premium Home gift: Mug.",
  },
  {
    name: "Mug",
    price: 1300,
    category: "Home",
    image: "/gifts/Mug 9.avif",
    description: "Premium Home gift: Mug.",
  },
  {
    name: "Mug",
    price: 1350,
    category: "Home",
    image: "/gifts/Mug 10.avif",
    description: "Premium Home gift: Mug.",
  },
  {
    name: "Tech Gift",
    price: 1000,
    category: "Tech",
    image: "/gifts/Tech 1.avif",
    description: "Premium Tech gift: Tech Gift.",
  },
  {
    name: "Tech Gift",
    price: 1100,
    category: "Tech",
    image: "/gifts/Tech 2.avif",
    description: "Premium Tech gift: Tech Gift.",
  },
  {
    name: "Tech Gift",
    price: 1200,
    category: "Tech",
    image: "/gifts/Tech 3.avif",
    description: "Premium Tech gift: Tech Gift.",
  },
  {
    name: "Tech Gift",
    price: 1300,
    category: "Tech",
    image: "/gifts/Tech 4.avif",
    description: "Premium Tech gift: Tech Gift.",
  },
  {
    name: "Tech Gift",
    price: 1400,
    category: "Tech",
    image: "/gifts/Tech 5.avif",
    description: "Premium Tech gift: Tech Gift.",
  },
  {
    name: "Tech Gift",
    price: 1500,
    category: "Tech",
    image: "/gifts/Tech 6.avif",
    description: "Premium Tech gift: Tech Gift.",
  },
  {
    name: "Tech Gift",
    price: 1600,
    category: "Tech",
    image: "/gifts/Tech 7.avif",
    description: "Premium Tech gift: Tech Gift.",
  },
  {
    name: "Tech Gift",
    price: 1700,
    category: "Tech",
    image: "/gifts/Tech 8.avif",
    description: "Premium Tech gift: Tech Gift.",
  },
  {
    name: "Tech Gift",
    price: 1800,
    category: "Tech",
    image: "/gifts/Tech 9.avif",
    description: "Premium Tech gift: Tech Gift.",
  },
  {
    name: "Tech Gift",
    price: 1900,
    category: "Tech",
    image: "/gifts/Tech 10.avif",
    description: "Premium Tech gift: Tech Gift.",
  },
  {
    name: "Watch",
    price: 2000,
    category: "Tech",
    image: "/gifts/Watch F1.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 2100,
    category: "Tech",
    image: "/gifts/Watch F2.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 2200,
    category: "Tech",
    image: "/gifts/Watch F3.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 2300,
    category: "Tech",
    image: "/gifts/Watch F4.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 2400,
    category: "Tech",
    image: "/gifts/Watch F5.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 2500,
    category: "Tech",
    image: "/gifts/Watch F6.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 2600,
    category: "Tech",
    image: "/gifts/Watch F7.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 2700,
    category: "Tech",
    image: "/gifts/Watch F8.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 2800,
    category: "Tech",
    image: "/gifts/Watch F9.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 2900,
    category: "Tech",
    image: "/gifts/Watch F10.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 3000,
    category: "Tech",
    image: "/gifts/Watch M1.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 3100,
    category: "Tech",
    image: "/gifts/Watch M2.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 3200,
    category: "Tech",
    image: "/gifts/Watch M3.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 3300,
    category: "Tech",
    image: "/gifts/Watch M4.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 3400,
    category: "Tech",
    image: "/gifts/Watch M5.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 3500,
    category: "Tech",
    image: "/gifts/Watch M6.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 3600,
    category: "Tech",
    image: "/gifts/Watch M7.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 3700,
    category: "Tech",
    image: "/gifts/Watch M8.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 3800,
    category: "Tech",
    image: "/gifts/Watch M9.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Watch",
    price: 3900,
    category: "Tech",
    image: "/gifts/Watch M10.avif",
    description: "Premium Tech gift: Watch.",
  },
  {
    name: "Travel Gift",
    price: 700,
    category: "Travel",
    image: "/gifts/Travel 1.avif",
    description: "Premium Travel gift: Travel Gift.",
  },
  {
    name: "Travel Gift",
    price: 750,
    category: "Travel",
    image: "/gifts/Travel 2.avif",
    description: "Premium Travel gift: Travel Gift.",
  },
  {
    name: "Travel Gift",
    price: 800,
    category: "Travel",
    image: "/gifts/Travel 3.avif",
    description: "Premium Travel gift: Travel Gift.",
  },
  {
    name: "Travel Gift",
    price: 850,
    category: "Travel",
    image: "/gifts/Travel 4.avif",
    description: "Premium Travel gift: Travel Gift.",
  },
  {
    name: "Travel Gift",
    price: 900,
    category: "Travel",
    image: "/gifts/Travel 5.avif",
    description: "Premium Travel gift: Travel Gift.",
  },
  {
    name: "Travel Gift",
    price: 950,
    category: "Travel",
    image: "/gifts/Travel 6.avif",
    description: "Premium Travel gift: Travel Gift.",
  },
  {
    name: "Travel Gift",
    price: 1000,
    category: "Travel",
    image: "/gifts/Travel 7.avif",
    description: "Premium Travel gift: Travel Gift.",
  },
  {
    name: "Travel Gift",
    price: 1050,
    category: "Travel",
    image: "/gifts/Travel 8.avif",
    description: "Premium Travel gift: Travel Gift.",
  },
  {
    name: "Travel Gift",
    price: 1100,
    category: "Travel",
    image: "/gifts/Travel 9.avif",
    description: "Premium Travel gift: Travel Gift.",
  },
  {
    name: "Travel Gift",
    price: 1150,
    category: "Travel",
    image: "/gifts/Travel 10.avif",
    description: "Premium Travel gift: Travel Gift.",
  },
];
